# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T00cf3DkYI4JD9r-274TLRDoRv5TtUzE
"""

'''Creating a calculator'''

"""REGRA UTILIZE A FUNÇÃO EM SUA FORMA PURA"""

#1 CRIE UMA FUNÇÃO PARA SUBTRAIR UM NÚMERO

f = int(input('digite un número -> '))
x = int(input('digite outro número -> '))
resultado = f - x
def sub(f):
    if resultado <= 0 or resultado == 0:
      print('seu resultado foi ->' ,resultado)
    elif resultado >= 0:
      print('Seu resultado será ->', resultado)
sub('b')

# #2 CRIE UMA FUNÇÃO PARA SOMAR UM NÚMERO

p = int(input('digite un número -> '))
y = int(input('digite outro número -> '))
resultado = p + y
def ad(p):
    if resultado == 0:
      print('seu resultado é ->' ,resultado)
    elif resultado >= 0:
      print('Seu resultado foi ->', resultado)
ad('b')

# #3 CRIE UMA FUNÇÃO PARA DIVIDIR UM NÚEMRO

q = int(input('digite un número -> '))
h = int(input('digite outro número -> '))
resultado = q / h
def div(q):
    if resultado == 0 or resultado <= 0:
      print('seu resultado é ->' ,resultado)
    elif resultado >= 0:
      print('Seu resultado foi ->', resultado)
div('b')

# #4 CRIE UMA FUNÇÃO PARA MULTIPLICAR DOIS NÚMEROS

m = int(input('digite un número -> '))
n = int(input('digite outro número -> '))
resultado = m * n
def mult(m):
    if resultado == 0 or resultado <= 0:
      print('seu resultado é ->' ,resultado)
    elif resultado >= 0:
      print('Seu resultado foi ->', resultado)
mult('b')

#5 CRIE UMA CALCULADORA, ONDE O USUÁRIO POSSO ESCOLHER AS OPERAÇÕES

num_calc = int(input('digite um número -> '))
operacao = input('qual operação vc deseja usar? -> ')
num_calc1 = int(input('digite outro numero -> '))

def calculadora():
   if operacao == '+':
    print(num_calc + num_calc1)
   elif operacao == '-':
      print(num_calc - num_calc1)
   elif operacao == '*':
      print(num_calc * num_calc1)
   elif operacao == '/':
       print(num_calc / num_calc1)

calculadora()

#DICA - UTILIZE CONDICIONAIS